[workspace]
resolver = "2"
members = [
    "crates/minipg-core",
    "crates/minipg-ast",
    "crates/minipg-parser",
    "crates/minipg-analysis",
    "crates/minipg-codegen",
    "crates/minipg-cli",
    "crates/minipg-benchmarks",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["minipg contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/minipg"

[workspace.dependencies]
# Internal crates
minipg-core = { path = "crates/minipg-core" }
minipg-ast = { path = "crates/minipg-ast" }
minipg-parser = { path = "crates/minipg-parser" }
minipg-analysis = { path = "crates/minipg-analysis" }
minipg-codegen = { path = "crates/minipg-codegen" }

# External dependencies
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive", "cargo"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
pulldown-cmark = "0.12"

# Testing
insta = { version = "1.41", features = ["yaml"] }
criterion = "0.5"
proptest = "1.5"
