[package]
name = "minipg-fuzz"
version = "0.0.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies.minipg]
path = ".."

[dependencies]
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_parser"
path = "fuzz_targets/fuzz_parser.rs"

