//! Tree-sitter code generator.
//!
//! Generates grammar.js files for Tree-sitter parser generator.
//! Tree-sitter is used by editors like VS Code, Neovim, and Atom for
//! syntax highlighting and code analysis.

use minipg_antlr::{Alternative, Element, Grammar, Rule};
use minipg_core::{types::CodeGenConfig, CodeGenerator as CodeGeneratorTrait, Result};

/// Tree-sitter code generator.
pub struct TreeSitterCodeGenerator;

impl TreeSitterCodeGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate the main grammar.js file
    fn generate_grammar_js(&self, grammar: &Grammar) -> String {
        let mut code = String::new();

        // Header comment
        code.push_str("/**\n");
        code.push_str(&format!(" * Tree-sitter grammar for {}\n", grammar.name));
        code.push_str(" * Generated by minipg from ANTLR4 grammar\n");
        code.push_str(" */\n\n");

        // Module exports
        code.push_str("module.exports = grammar({\n");
        code.push_str(&format!(
            "  name: '{}',\n\n",
            self.to_snake_case(&grammar.name)
        ));

        // Extras (whitespace and comments)
        code.push_str("  extras: $ => [\n");
        code.push_str("    /\\s/,\n");
        code.push_str("  ],\n\n");

        // Rules
        code.push_str("  rules: {\n");

        // Find the start rule (first parser rule)
        if let Some(_start_rule) = grammar.parser_rules().next() {
            // Generate all parser rules
            for rule in grammar.parser_rules() {
                code.push_str(&self.generate_rule(rule, grammar));
            }

            // Generate lexer rules as tokens
            for rule in grammar.lexer_rules() {
                code.push_str(&self.generate_token_rule(rule));
            }
        }

        code.push_str("  }\n");
        code.push_str("});\n");

        code
    }

    /// Generate a parser rule
    fn generate_rule(&self, rule: &Rule, grammar: &Grammar) -> String {
        let mut code = String::new();

        code.push_str(&format!("    {}: $ => ", self.to_snake_case(&rule.name)));

        if rule.alternatives.len() == 1 {
            code.push_str(&self.generate_alternative(&rule.alternatives[0], grammar));
        } else {
            code.push_str("choice(\n");
            for (i, alt) in rule.alternatives.iter().enumerate() {
                code.push_str("      ");
                code.push_str(&self.generate_alternative(alt, grammar));
                if i < rule.alternatives.len() - 1 {
                    code.push_str(",\n");
                } else {
                    code.push_str("\n");
                }
            }
            code.push_str("    )");
        }

        code.push_str(",\n\n");
        code
    }

    /// Generate a token/lexer rule
    fn generate_token_rule(&self, rule: &Rule) -> String {
        let mut code = String::new();

        code.push_str(&format!("    {}: $ => ", self.to_snake_case(&rule.name)));

        if rule.alternatives.len() == 1 {
            code.push_str(&self.generate_token_alternative(&rule.alternatives[0]));
        } else {
            code.push_str("choice(\n");
            for (i, alt) in rule.alternatives.iter().enumerate() {
                code.push_str("      ");
                code.push_str(&self.generate_token_alternative(alt));
                if i < rule.alternatives.len() - 1 {
                    code.push_str(",\n");
                } else {
                    code.push_str("\n");
                }
            }
            code.push_str("    )");
        }

        code.push_str(",\n\n");
        code
    }

    /// Generate an alternative for parser rules
    fn generate_alternative(&self, alt: &Alternative, grammar: &Grammar) -> String {
        if alt.elements.is_empty() {
            return "''".to_string();
        }

        if alt.elements.len() == 1 {
            return self.generate_element(&alt.elements[0], grammar);
        }

        let mut parts = Vec::new();
        for elem in &alt.elements {
            parts.push(self.generate_element(elem, grammar));
        }

        format!("seq({})", parts.join(", "))
    }

    /// Generate an alternative for token rules
    fn generate_token_alternative(&self, alt: &Alternative) -> String {
        if alt.elements.is_empty() {
            return "''".to_string();
        }

        if alt.elements.len() == 1 {
            return self.generate_token_element(&alt.elements[0]);
        }

        let mut parts = Vec::new();
        for elem in &alt.elements {
            parts.push(self.generate_token_element(elem));
        }

        format!("seq({})", parts.join(", "))
    }

    /// Generate an element for parser rules
    fn generate_element(&self, elem: &Element, grammar: &Grammar) -> String {
        match elem {
            Element::RuleRef { name, .. } => {
                // Check if this is a lexer or parser rule
                if let Some(rule) = grammar.get_rule(name) {
                    if rule.is_lexer_rule() {
                        format!("$.{}", self.to_snake_case(name))
                    } else {
                        format!("$.{}", self.to_snake_case(name))
                    }
                } else {
                    format!("$.{}", self.to_snake_case(name))
                }
            }
            Element::StringLiteral { value, .. } | Element::Terminal { value, .. } => {
                format!("'{}'", self.escape_string(value))
            }
            Element::CharClass { negated, ranges } => {
                let chars = self.format_char_ranges(ranges);
                if *negated {
                    format!("/[^{}]/", chars)
                } else {
                    format!("/[{}]/", chars)
                }
            }
            Element::Optional { element, .. } => {
                let inner = self.generate_element(element, grammar);
                format!("optional({})", inner)
            }
            Element::ZeroOrMore { element, .. } => {
                let inner = self.generate_element(element, grammar);
                format!("repeat({})", inner)
            }
            Element::OneOrMore { element, .. } => {
                let inner = self.generate_element(element, grammar);
                format!("repeat1({})", inner)
            }
            Element::Group { alternatives } => {
                if alternatives.len() == 1 {
                    self.generate_alternative(&alternatives[0], grammar)
                } else {
                    let mut parts = Vec::new();
                    for alt in alternatives {
                        parts.push(self.generate_alternative(alt, grammar));
                    }
                    format!("choice({})", parts.join(", "))
                }
            }
            Element::Action { .. } | Element::Predicate { .. } => {
                // Tree-sitter doesn't support actions/predicates
                "''".to_string()
            }
            Element::Wildcard => "/./".to_string(),
            _ => "''".to_string(),
        }
    }

    /// Generate an element for token rules
    fn generate_token_element(&self, elem: &Element) -> String {
        match elem {
            Element::StringLiteral { value, .. } | Element::Terminal { value, .. } => {
                format!("'{}'", self.escape_string(value))
            }
            Element::CharClass { negated, ranges } => {
                let chars = self.format_char_ranges(ranges);
                if *negated {
                    format!("/[^{}]/", chars)
                } else {
                    format!("/[{}]/", chars)
                }
            }
            Element::Optional { element, .. } => {
                let inner = self.generate_token_element(element);
                format!("optional({})", inner)
            }
            Element::ZeroOrMore { element, .. } => {
                let inner = self.generate_token_element(element);
                format!("repeat({})", inner)
            }
            Element::OneOrMore { element, .. } => {
                let inner = self.generate_token_element(element);
                format!("repeat1({})", inner)
            }
            Element::Group { alternatives } => {
                if alternatives.len() == 1 {
                    self.generate_token_alternative(&alternatives[0])
                } else {
                    let mut parts = Vec::new();
                    for alt in alternatives {
                        parts.push(self.generate_token_alternative(alt));
                    }
                    format!("choice({})", parts.join(", "))
                }
            }
            Element::RuleRef { name, .. } => {
                format!("$.{}", self.to_snake_case(name))
            }
            Element::Wildcard => "/./".to_string(),
            _ => "''".to_string(),
        }
    }

    /// Generate package.json for Tree-sitter
    fn generate_package_json(&self, grammar: &Grammar) -> String {
        let mut code = String::new();

        code.push_str("{\n");
        code.push_str(&format!(
            "  \"name\": \"tree-sitter-{}\",\n",
            self.to_kebab_case(&grammar.name)
        ));
        code.push_str("  \"version\": \"0.1.0\",\n");
        code.push_str(&format!(
            "  \"description\": \"Tree-sitter grammar for {}\",\n",
            grammar.name
        ));
        code.push_str("  \"main\": \"bindings/node\",\n");
        code.push_str("  \"keywords\": [\n");
        code.push_str("    \"tree-sitter\",\n");
        code.push_str("    \"parser\"\n");
        code.push_str("  ],\n");
        code.push_str("  \"dependencies\": {\n");
        code.push_str("    \"nan\": \"^2.17.0\"\n");
        code.push_str("  },\n");
        code.push_str("  \"devDependencies\": {\n");
        code.push_str("    \"tree-sitter-cli\": \"^0.20.8\"\n");
        code.push_str("  },\n");
        code.push_str("  \"tree-sitter\": [\n");
        code.push_str("    {\n");
        code.push_str(&format!(
            "      \"scope\": \"source.{}\",\n",
            self.to_snake_case(&grammar.name)
        ));
        code.push_str("      \"file-types\": []\n");
        code.push_str("    }\n");
        code.push_str("  ]\n");
        code.push_str("}\n");

        code
    }

    /// Generate README.md
    fn generate_readme(&self, grammar: &Grammar) -> String {
        let mut code = String::new();

        code.push_str(&format!(
            "# tree-sitter-{}\n\n",
            self.to_kebab_case(&grammar.name)
        ));
        code.push_str(&format!("Tree-sitter grammar for {}\n\n", grammar.name));
        code.push_str("## Installation\n\n");
        code.push_str("```bash\n");
        code.push_str("npm install\n");
        code.push_str("```\n\n");
        code.push_str("## Building\n\n");
        code.push_str("```bash\n");
        code.push_str("tree-sitter generate\n");
        code.push_str("tree-sitter build\n");
        code.push_str("```\n\n");
        code.push_str("## Testing\n\n");
        code.push_str("```bash\n");
        code.push_str("tree-sitter test\n");
        code.push_str("```\n\n");
        code.push_str("## Usage\n\n");
        code.push_str("This grammar can be used with any editor that supports Tree-sitter:\n\n");
        code.push_str("- Neovim\n");
        code.push_str("- Emacs\n");
        code.push_str("- Atom\n");
        code.push_str("- VS Code (with extensions)\n\n");
        code.push_str("## Generated by minipg\n\n");
        code.push_str("This grammar was automatically generated from an ANTLR4 grammar using [minipg](https://github.com/yingkitw/minipg).\n");

        code
    }

    /// Convert PascalCase to snake_case
    fn to_snake_case(&self, s: &str) -> String {
        let mut result = String::new();
        let chars: Vec<char> = s.chars().collect();

        for (i, &c) in chars.iter().enumerate() {
            if c.is_uppercase() {
                // Add underscore before uppercase if:
                // 1. Not the first character
                // 2. Previous character is lowercase OR
                // 3. Next character is lowercase (for acronyms like "JSON")
                if i > 0 {
                    let prev_is_lower = chars.get(i - 1).map(|c| c.is_lowercase()).unwrap_or(false);
                    let next_is_lower = chars.get(i + 1).map(|c| c.is_lowercase()).unwrap_or(false);

                    if prev_is_lower || (i > 0 && next_is_lower && chars[i - 1].is_uppercase()) {
                        result.push('_');
                    }
                }
                result.push(c.to_lowercase().next().unwrap());
            } else {
                result.push(c);
            }
        }

        result
    }

    /// Convert PascalCase to kebab-case
    fn to_kebab_case(&self, s: &str) -> String {
        self.to_snake_case(s).replace('_', "-")
    }

    /// Escape string for JavaScript
    fn escape_string(&self, s: &str) -> String {
        s.replace('\\', "\\\\")
            .replace('\'', "\\'")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t")
    }

    /// Format character ranges for regex
    fn format_char_ranges(&self, ranges: &[(char, char)]) -> String {
        let mut result = String::new();
        for (start, end) in ranges {
            if start == end {
                result.push_str(&self.escape_char_for_regex(*start));
            } else {
                result.push_str(&self.escape_char_for_regex(*start));
                result.push('-');
                result.push_str(&self.escape_char_for_regex(*end));
            }
        }
        result
    }

    /// Escape a character for use in regex character class
    fn escape_char_for_regex(&self, c: char) -> String {
        match c {
            '\\' => "\\\\".to_string(),
            ']' => "\\]".to_string(),
            '^' => "\\^".to_string(),
            '-' => "\\-".to_string(),
            _ => c.to_string(),
        }
    }
}

impl Default for TreeSitterCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGeneratorTrait for TreeSitterCodeGenerator {
    type Input = Grammar;
    type Config = CodeGenConfig;

    fn generate(&self, grammar: &Grammar, _config: &CodeGenConfig) -> Result<String> {
        let mut output = String::new();

        output.push_str("// File: grammar.js\n");
        output.push_str("// ==================\n\n");
        output.push_str(&self.generate_grammar_js(grammar));

        output.push_str("\n\n// File: package.json\n");
        output.push_str("// ==================\n\n");
        output.push_str(&self.generate_package_json(grammar));

        output.push_str("\n\n// File: README.md\n");
        output.push_str("// ==================\n\n");
        output.push_str(&self.generate_readme(grammar));

        Ok(output)
    }

    fn target_language(&self) -> &str {
        "treesitter"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use minipg_antlr::{ast::Alternative, ast::Element, ast::Rule, ast::RuleType};
    use minipg_core::types::GrammarType;

    #[test]
    fn test_generate_simple_grammar() {
        let mut grammar = Grammar::new("Calculator".to_string(), GrammarType::Combined);

        let mut expr_rule = Rule::new("expr".to_string(), RuleType::Parser);
        let mut alt = Alternative::new();
        alt.add_element(Element::RuleRef {
            name: "term".to_string(),
            label: None,
            is_list: false,
        });
        expr_rule.add_alternative(alt);
        grammar.add_rule(expr_rule);

        let mut term_rule = Rule::new("term".to_string(), RuleType::Parser);
        let mut alt = Alternative::new();
        alt.add_element(Element::RuleRef {
            name: "NUMBER".to_string(),
            label: None,
            is_list: false,
        });
        term_rule.add_alternative(alt);
        grammar.add_rule(term_rule);

        let mut number_rule = Rule::new("NUMBER".to_string(), RuleType::Lexer);
        let mut alt = Alternative::new();
        alt.add_element(Element::CharClass {
            negated: false,
            ranges: vec![('0', '9')],
        });
        number_rule.add_alternative(alt);
        grammar.add_rule(number_rule);

        let generator = TreeSitterCodeGenerator::new();
        let config = CodeGenConfig::default();
        let result = generator.generate(&grammar, &config);

        assert!(result.is_ok());
        let code = result.unwrap();
        assert!(code.contains("module.exports = grammar"));
        assert!(code.contains("name: 'calculator'"));
        assert!(code.contains("expr:"));
        assert!(code.contains("term:"));
        assert!(code.contains("number:"));
    }

    #[test]
    fn test_snake_case_conversion() {
        let generator = TreeSitterCodeGenerator::new();
        assert_eq!(generator.to_snake_case("Calculator"), "calculator");
        assert_eq!(generator.to_snake_case("MyGrammar"), "my_grammar");
        assert_eq!(generator.to_snake_case("JSONParser"), "json_parser");
    }

    #[test]
    fn test_kebab_case_conversion() {
        let generator = TreeSitterCodeGenerator::new();
        assert_eq!(generator.to_kebab_case("Calculator"), "calculator");
        assert_eq!(generator.to_kebab_case("MyGrammar"), "my-grammar");
        assert_eq!(generator.to_kebab_case("JSONParser"), "json-parser");
    }

    #[test]
    fn test_generate_with_literals() {
        let mut grammar = Grammar::new("Test".to_string(), GrammarType::Combined);

        let mut rule = Rule::new("test".to_string(), RuleType::Parser);
        let mut alt = Alternative::new();
        alt.add_element(Element::StringLiteral {
            value: "hello".to_string(),
            label: None,
            is_list: false,
        });
        rule.add_alternative(alt);
        grammar.add_rule(rule);

        let generator = TreeSitterCodeGenerator::new();
        let config = CodeGenConfig::default();
        let result = generator.generate(&grammar, &config);

        assert!(result.is_ok());
        let code = result.unwrap();
        assert!(code.contains("'hello'"));
    }

    #[test]
    fn test_generate_with_quantifiers() {
        let mut grammar = Grammar::new("Test".to_string(), GrammarType::Combined);

        let mut rule = Rule::new("test".to_string(), RuleType::Parser);
        let mut alt = Alternative::new();
        alt.add_element(Element::ZeroOrMore {
            element: Box::new(Element::StringLiteral {
                value: "a".to_string(),
                label: None,
                is_list: false,
            }),
            greedy: true,
        });
        rule.add_alternative(alt);
        grammar.add_rule(rule);

        let generator = TreeSitterCodeGenerator::new();
        let config = CodeGenConfig::default();
        let result = generator.generate(&grammar, &config);

        assert!(result.is_ok());
        let code = result.unwrap();
        assert!(code.contains("repeat("));
    }

    #[test]
    fn test_generate_package_json() {
        let grammar = Grammar::new("MyLang".to_string(), GrammarType::Combined);
        let generator = TreeSitterCodeGenerator::new();
        let package_json = generator.generate_package_json(&grammar);

        assert!(package_json.contains("\"name\": \"tree-sitter-my-lang\""));
        assert!(package_json.contains("\"tree-sitter-cli\""));
    }

    #[test]
    fn test_generate_readme() {
        let grammar = Grammar::new("MyLang".to_string(), GrammarType::Combined);
        let generator = TreeSitterCodeGenerator::new();
        let readme = generator.generate_readme(&grammar);

        assert!(readme.contains("# tree-sitter-my-lang"));
        assert!(readme.contains("Tree-sitter grammar for MyLang"));
        assert!(readme.contains("minipg"));
    }
}
